### ISSUE TITLE
Slow performance when reading 1 line from large file

### ISSUE THREAD

**Issue by nromito** [SenorAgosto/cribl.io.test#1]
If you want just the last line of a file that's large (say 5GB), the performance is quite poor.

```
nromito-mbp:REST-log-collector nromito$ ls -lah /var/log/test.log
-rw-r--r--  1 nromito  staff   5.1G Jul  7 18:50 /var/log/test.log
nromito-mbp:REST-log-collector nromito$ time http :8888/log/test.log/1
HTTP/1.1 200 OK
Content-Length: 137
Content-Type: text/plain; charset=utf-8
Date: Wed, 07 Jul 2021 23:53:19 GMT
Server: Rocket

Jun 23 14:17:49 nick-VirtualBox whoopsie[1198]: [14:17:49] The default IPv4 route is: /org/freedesktop/NetworkManager/ActiveConnection/1



real	0m49.526s
user	0m0.300s
sys	0m0.100s
```

Takes around 1 minute to get one line

**Comment by SenorAgosto** [comment]
@nromito thanks for filing the issue, I pushed some commits that should fix the performance of the naive implementation I submitted initially. 

- memory map the file
- parse the log lines from the end of the memory mapped file forward
- use Boyer-Moore string search algorithm instead of `std::String::contains()`

This means we no longer read the entire file to get the latest event, we find events starting at the end of the file and working forward. This also means the filtering performance should increase with longer keywords rather than decrease (as they did in the naive implementation).
